"""
signals/groq_classifier.py — Signal 1: LLM-based AI authorship classifier.

Sends text to the Groq API with a structured prompt and parses a 0–1
probability score out of the response. Returns 0.5 on any failure so
the system degrades gracefully to heuristics-only rather than crashing.

Output contract (from planning.md §2, §8):
    float in [0.0, 1.0]
    0.0 = classifier is confident the text is human-written
    1.0 = classifier is confident the text is AI-generated
"""

import os
import re
import json
from groq import Groq

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise EnvironmentError("GROQ_API_KEY is not set in environment.")
        _client = Groq(api_key=api_key)
    return _client


SYSTEM_PROMPT = """You are an AI authorship detection system. Your job is to assess
whether a piece of text was written by a human or generated by an AI language model.

Analyse the text for these indicators:
- AI indicators: suspiciously uniform sentence structure, over-explained transitions,
  hedging language clusters ("it's important to note", "it's worth mentioning"),
  unnaturally balanced paragraph lengths, generic examples, absence of personal
  idiosyncrasies, perfect grammar throughout.
- Human indicators: topic drift, uneven elaboration, idiosyncratic word choices,
  rhetorical habits, small inconsistencies, personal voice, irregular punctuation,
  emotional register shifts.

You MUST respond with valid JSON only. No explanation, no preamble, no markdown fences.
Respond with exactly this structure:
{
  "ai_probability": <float between 0.0 and 1.0>,
  "reasoning": "<one sentence explanation>"
}

Where ai_probability is:
  0.0 = definitely human-written
  1.0 = definitely AI-generated
  0.5 = genuinely uncertain"""

USER_PROMPT_TEMPLATE = """Assess the following text for AI authorship:

---
{text}
---

Respond with JSON only."""


def groq_classifier(text: str) -> float:
    """
    Send text to Groq and return a 0–1 AI-probability score.

    Falls back to 0.5 on any error (API failure, parse failure, etc.)
    so the system can continue with heuristic signals only.
    """
    if not text or not text.strip():
        return 0.5

    # Truncate to ~3000 words to stay within token limits while keeping signal quality
    words = text.split()
    if len(words) > 3000:
        text = " ".join(words[:3000]) + " [truncated]"

    try:
        client = _get_client()
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": USER_PROMPT_TEMPLATE.format(text=text)},
            ],
            temperature=0.1,   # Low temperature for consistent structured output
            max_tokens=200,
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown fences if the model adds them despite instructions
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)

        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])

        # Clamp to [0, 1] in case the model returns e.g. 1.05
        return max(0.0, min(1.0, score))

    except Exception as exc:
        # Log to stderr but do not crash — return neutral 0.5
        import sys
        print(f"[groq_classifier] Error: {exc}", file=sys.stderr)
        return 0.5